FROM php:8.3.0-apache

RUN groupadd -g 1000 appuser && useradd -r -u 1000 -g appuser appuser

RUN apt-get update && \
    apt-get install -y unzip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www
COPY config/vhost.conf /etc/apache2/sites-available/000-default.conf
RUN a2ensite 000-default.conf && \
    a2enmod rewrite

RUN chown -R appuser:appuser /var/www
USER appuser
COPY composer.json /var/www/composer.json
RUN composer install
